/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validations;

import Alerts.showAlerts;
import Model.wallpaper;

/**
 *
 * @author sebastian.londono
 */
public class squemaWallpaper extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    showAlerts alerts = new showAlerts();

    public squemaWallpaper() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validation_wallpaper(wallpaper dataWallpaper) {
        //Description
        if (dataWallpaper.getDescription().equals("")) {
            alerts.alert("La descripción es obligatoria");
            return false;
        }
        if (dataWallpaper.getDescription().length() > 50) {
            alerts.alert("La descripción es máximo de 50 caracteres");
            return false;
        }
        if (dataWallpaper.getDescription().length() < 5) {
            alerts.alert("La descripción es minimo de 5 caracteres");
            return false;
        }

        //ImageUrl
        if (dataWallpaper.getImageURL().equals("")) {
            alerts.alert("La imagen es obligatoria");
            return false;
        }
        if (dataWallpaper.getImageURL().length() > 20) {
            alerts.alert("La imagen máximo de 20 caracteres");
            return false;
        }

        //Cantidad
        if (dataWallpaper.getCantPage() <= 0) {
            alerts.alert("La cantidad por hoja debe ser mayor a 0");
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
