/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validations;

import Alerts.showAlerts;
import Model.user;

/**
 *
 * @author sebastian.londono
 */
public class squemaLanding extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    showAlerts alerts = new showAlerts();

    public squemaLanding() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validation_landing(String username, String password) {

        //Username
        if (username.equals("")) {
            alerts.alert("El usuario es obligatorio");
            return false;
        }
        if (username.length() > 20) {
            alerts.alert("El usuario es máximo de 20 caracteres");
            return false;
        }
        if (username.length() < 5) {
            alerts.alert("El usuario es minimo de 5 caracteres");
            return false;
        }

        //Password
        if (password.equals("")) {
            alerts.alert("La contraseña es obligatoria");
            return false;
        }
        if (password.length() > 20) {
            alerts.alert("La contraseña es máximo de 20 caracteres");
            return false;
        }
        if (password.length() < 5) {
            alerts.alert("La contraseña es minimo de 5 caracteres");
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
