/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validations;

import Alerts.showAlerts;
import Model.product;

/**
 *
 * @author sebastian.londono
 */
public class squemaProduct extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    showAlerts alerts = new showAlerts();

    public squemaProduct() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validation_product(product dataProduct) {
        //Name
        if (dataProduct.getCodeProduct().equals("")) {
            alerts.alert("El codigo es obligatorio");
            return false;
        }
        if (dataProduct.getCodeProduct().length() > 25) {
            alerts.alert("El codigo es máximo de 25 caracteres");
            return false;
        }
        if (dataProduct.getCodeProduct().length() < 1) {
            alerts.alert("El codigo es minimo de 1 caracteres");
            return false;
        }

        //Description
        if (dataProduct.getDescription().length() > 75) {
            alerts.alert("La descripcion es máximo de 75 caracteres");
            return false;
        }
        if (!dataProduct.getDescription().equals("") & dataProduct.getDescription().length() < 5) {
            alerts.alert("La descripcion es minimo de 5 caracteres");
            return false;
        }

        //Price
        if (dataProduct.getPrice() == null) {
            alerts.alert("El precio es obligatorio");
            return false;
        }
        if (dataProduct.getPrice() <= 0) {
            alerts.alert("El precio tiene que ser mayor a 0");
            return false;
        }

        //Cant
        if (dataProduct.getCant() == null) {
            alerts.alert("La cantidad es obligatoria");
            return false;
        }
        if (dataProduct.getCant() <= 0) {
            alerts.alert("El cantidad tiene que ser mayor a 0");
            return false;
        }

        //Description1
        if (dataProduct.getDescription1().length() > 75) {
            alerts.alert("La descripcion1 es máximo de 75 caracteres");
            return false;
        }
        if (!dataProduct.getDescription1().equals("") & dataProduct.getDescription1().length() < 5) {
            alerts.alert("La descripcion1 es minimo de 5 caracteres");
            return false;
        }

        //Description2
        if (dataProduct.getDescription2().length() > 75) {
            alerts.alert("La descripcion1 es máximo de 75 caracteres");
            return false;
        }
        if (!dataProduct.getDescription2().equals("") & dataProduct.getDescription2().length() < 5) {
            alerts.alert("La descripcion1 es minimo de 5 caracteres");
            return false;
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
