/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Validations;

import Alerts.showAlerts;

/**
 *
 * @author sebastian.londono
 */
public class squemaMarketplace extends javax.swing.JPanel {

    /**
     * Creates new form squemaProduct
     */
    showAlerts alerts = new showAlerts();

    public squemaMarketplace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public boolean validation_marketplace(int products, String wallpaper, String cover) {

        //Products
        if (products <= 0) {
            alerts.alert("No hay productos cargados");
            return false;
        }

        int count = 0;
        if (wallpaper.equals("")) {
            alerts.alert("No ha seleccionado el fondo de pantalla");
            count++;
        }

        if (cover.equals("")) {
            alerts.alert("No ha seleccionado la portada");
            count++;
        }

        if (count > 0) {
            if (!alerts.option("¿Desea continuar?")) {
                return false;
            }
        }

        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
